#!/usr/bin/env ruby

$LOAD_PATH.unshift(File.expand_path(File.join(File.dirname(__FILE__), '../lib')))

require 'cfb'
require 'cfb/merge_lines_and_schedule'

CFB::MergeLinesAndSchedule.run(lines: ARGV[0], schedule: ARGV[1])
